name: Weekly Finance Report

on:
  schedule:
    # Every Monday 04:30 UTC (≈ 10:00 IST)
    - cron: "30 4 * * 1"
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      # Email (set in Repo → Settings → Secrets and variables → Actions → New repository secret)
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      # Telegram (optional)
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly summary (notify)
        run: |
          python scripts/weekly_summary.py --input_glob "data/*.csv" --output outputs --days 7 --notify

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: weekly-finance-report-${{ github.run_id }}
          path: outputs/**
